version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
      - "444:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - dotnet
    networks:
      - my-network

  dotnet:
    container_name: dotnet
    image: mcr.microsoft.com/dotnet/sdk:8.0
    ports:
      - "5001:8080"
    volumes:
      - ./app1:/app1
      - ./dotnet80100:/dotnet80100
    command: bash -c "ln -s /app1/wwwroot/ /wwwroot && /dotnet80100/dotnet /app1/Niu.Living.dll"
    networks:
      - my-network

networks:
  my-network: