pipeline {
    agent any

    stages {
        stage('Sync s3') {
            steps {
                script {
                    withCredentials([
                        [$class: 'AmazonWebServicesCredentialsBinding', 
                         accessKeyVariable: 'AWS_ACCESS_KEY_ID', 
                         secretKeyVariable: 'AWS_SECRET_ACCESS_KEY', 
                         credentialsId: '62c39d7a-6bdc-474a-9d4f-7c379e3b7c9d']
                    ]) {
                        sshagent(['7fd9e024-a02b-4745-ae76-2921235d9980']) {
                            sh '''
                            ssh -o StrictHostKeyChecking=no ec2-user@3.237.10.253 \
                                "export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}; \
                                export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}; \
                                aws s3 sync s3://docker-image3424644/app1/ /var/lib/docker/volumes/niutecklandpage_prd_app/_data; \
                                aws s3 sync s3://docker-image3424644/Niu.Living /home/ec2-user/Niu.Living; \
                                aws s3 sync s3://docker-image3424644/dotnet80100 /home/ec2-user/dotnet-docker-pipeline/dotnet80100;"
                            '''
                        }
                    }
                }
            }
        }

        stage('Run dotnet publish') {
            steps {
                script {
                    sshagent(['7fd9e024-a02b-4745-ae76-2921235d9980']) {
                        sh '''
                        ssh -o StrictHostKeyChecking=no ec2-user@3.237.10.253 \
                            "cd /home/ec2-user/Niu.Living; \
                            sudo yum install libicu -y; \
                            chmod +x ~/dotnet-docker-pipeline/dotnet80100/dotnet; \
                            ~/dotnet-docker-pipeline/dotnet80100/dotnet build ~/Niu.Living/Niu.Living.sln --configuration Release;"
                        '''
                    }
                }
            }
        }

        stage('Clonar o repositório') {
            steps {
                script {
                    sshagent(['7fd9e024-a02b-4745-ae76-2921235d9980']) {
                        sh '''
                        ssh -o StrictHostKeyChecking=no ec2-user@3.237.10.253 \
                            "sudo yum install git -y; \
                            git clone https://github.com/fabiosleal2712/dotnet-docker-pipeline.git || true; \
                            cd /home/ec2-user/dotnet-docker-pipeline; \
                            git pull;"
                        '''
                    }
                }
            }
        }

        stage('Run Another Docker Container on EC2') {
            steps {
                script {
                    sshagent(['7fd9e024-a02b-4745-ae76-2921235d9980']) {
                        sh '''
                        ssh -o StrictHostKeyChecking=no ec2-user@3.237.10.253 \
                            "cd /home/ec2-user/dotnet-docker-pipeline; \
                            git pull; \
                            docker-compose down; \
                            docker-compose up -d;"
                        '''
                    }
                }
            }
        }
    }
}
